### PR TITLE
Bagpipes m1 delivery

### PR DESCRIPTION
**Pull request by flipchan**
## Grant link:
https://github.com/OAK-Foundation/Grants-Program/blob/main/applications/bagpipes_integration.md

## Project name: 
Bagpipes 

## Extra documentation:  
https://docs.bagpipes.io/docs/xtransfer/turing

### CODE REVIEW

**Comment by chrisli30** [comment]
Issue - The Wallet Selection page doesn’t close and block the rest of page after Sign-in with Polkadot.js wallet.
CleanShot 2024-04-21 at 11 54 16

I figured that by clicking on the left navbar button it can go to another page, but the process is not really intuitive.

**Comment by chrisli30** [comment]
Question - for the Turing -> Moonriver workflow I will need to load Ethereum wallet address, but how does the page load Talisman?

The Talisman is connected for the page but I got the below screenshot. What does "Add example metadata" mean? Clicking on it results in "Failed to add metadata" error.
CleanShot 2024-04-21 at 12 56 14

I’m blocked by this step to choose a correct target wallet on Moonriver. The Moonriver EVM address cannot be converted from Polkadot address, so an xToken transfer always needs manual selection of target wallet.

**Comment by chrisli30** [comment]
Issue - In Turing to Mangata scenario, after I approve the workflow how to sign the transaction? Only polkadot.js is connected and there is no prompt for signature from the Chrome plugin.
CleanShot 2024-04-21 at 13 01 45

**Comment by chrisli30** [comment]
Question - I do not understand the setting of the target amount function. For example, I am sending 100 TUR from Turing to Managata for 50 TUR. This scenario doesn’t really make sense, since if the token is the same they should be 1:1 mapped. Besides, since the unit per second is set in chain configs, for xToken transfer, there’s no way for users to specify the target amount to whatever they want.
CleanShot 2024-04-21 at 13 03 22

That said, the composed XCM message is different from the UI, in a sense that it doesn’t contain a targeted amount.

I’m curious, is there any pallet call that would allow user to set target amount?

**Comment by chrisli30** [comment]
In very rare cases, that chain A’s asset to be transferred into chain B’s other asset via XCM. Is there a feature already to whitelist target assets and grey out those unavailable?

For example, in Turing -> Mangata case, only TUR is available, and if you could combined the XCM transfer with swap, KSM, TUR, MGX would be available too.
CleanShot 2024-04-21 at 13 07 02

**Comment by chrisli30** [comment]
Is "Lab" for transaction or scenario histories? So far the name Lab sounds obscure to me.

CleanShot 2024-04-21 at 13 09 35

Also a nitpick - since Contracts and Settings pages are blank, I think we should either add a few line to explain the planned features, or not show them on the left nav bar.

**Comment by flipchan** [comment]
> Question - I do not understand the setting of the target amount function. For example, I am sending 100 TUR from Turing to Managata for 50 TUR. This scenario doesn’t really make sense, since if the token is the same they should be 1:1 mapped. Besides, since the unit per second is set in chain configs, for xToken transfer, there’s no way for users to specify the target amount to whatever they want. CleanShot 2024-04-21 at 13 03 22
> 
> That said, the composed XCM message is different from the UI, in a sense that it doesn’t contain a targeted amount.
> 
> I’m curious, is there any pallet call that would allow user to set target amount?

This is due to multiple hops, you will always see the sending amount in the action bar,  for example if you have a multi hop scenario like this:
Screenshot_2024-04-22_14-26-12


The action node in the middle displays the action, you only need to set the amount in the chain node your sending from

**Comment by flipchan** [comment]
> I’m blocked by this step to choose a correct target wallet on Moonriver. The Moonriver EVM address cannot be converted from Polkadot address, so an xToken transfer always needs manual selection of target wallet.

We have investigated this and we have added support for converting substrate accountid32 to evm addresses, however this is not universially stable, therefor we recommend to follow the video and manually select ur evm address(The problem is that the acocunt key generation for evm accounts/accountid20 types is not always working, so only some wallets lets you export your private key and convert it to a eth address, resulting in it being very hard for most polkadot account users to convert there ss58 seed to an eth address, resulting in problems accessing funds, this is the most stable way right now, we might add a filter moonriver nodes). 
Resources: 
https://github.com/polkadot-js/common/blob/f23f0944a85a6ddff72a8cd5866e85fd88edea39/packages/util-crypto/src/address/addressToEvm.ts#L9
unique is converting using the above functionality: https://github.com/UniqueNetwork/ts_api/blob/0d44ee0fdabd72a7c2225f32ab483a4eb8af4b05/src/utils/address/substrate.ts#L156C1-L157C1  
astar mentions this: https://medium.com/astar-network/using-astar-network-account-between-substrate-and-evm-656643df22a0  
same conversion in bagpipes: https://github.com/XcmSend/app/blob/1062a0f9e911f9930c2d9c18358d0a6528f9f484/src/Chains/Helpers/txHelper.ts#L19

**Comment by decentration** [comment]
> In very rare cases, that chain A’s asset to be transferred into chain B’s other asset via XCM. Is there a feature already to whitelist target assets and grey out those unavailable?
> 
> For example, in Turing -> Mangata case, only TUR is available, and if you could combined the XCM transfer with swap, KSM, TUR, MGX would be available too.

hey chris, 

> Is "Lab" for transaction or scenario histories? So far the name Lab sounds obscure to me.
> 
> CleanShot 2024-04-21 at 13 09 35
> 
> Also a nitpick - since Contracts and Settings pages are blank, I think we should either add a few line to explain the planned features, or not show them on the left nav bar.

hey chris, yes we can hide contacts and settings until they are ready. 

Do you prefer Scenarios than Lab? that is a fair point. Scenarios is more obvious.

**Comment by decentration** [comment]
> Issue - In Turing to Mangata scenario, after I approve the workflow how to sign the transaction? Only polkadot.js is connected and there is no prompt for signature from the Chrome plugin. CleanShot 2024-04-21 at 13 01 45

there should be a red notification in the polkadot js plugin, like below, do you have that? if so just click it and then the extension should pop up. 

Screenshot 2024-04-22 at 14 49 14

**Comment by decentration** [comment]
btw, thanks for the feedback! 

We are also working on the next larger release of bagpipes UI, which will include a new look similar to the UI mockups you received; and the ability for users to persist scenarios, which is going to be a game changer; also the ability to use logic pills to make condition based data flows... so a bunch of stuff will also be improved the OAK integrations will naturally benefit from those releases too.

**Comment by flipchan** [comment]
@chrisli30 Video turing 2 moonriver:
https://drive.google.com/file/d/1-dr8exA8TqwbuhJlqnkFnS-RkBGOm8YN/view?usp=sharing

Moonriver > Turing Video demo:
https://drive.google.com/file/d/1Jrl5DQzu_2t4iuBKVu_hyQqzdJ8HeL9B/view?usp=sharing

**Comment by flipchan** [comment]
@chrisli30 /lab section docs: https://docs.bagpipes.io/docs/intro/concepts#scenario can we make these docs clearer? or do you have any ideas on how we can better document the lab section

**Comment by decentration** [comment]
Regarding the changes @chrisli30 and @flipchan:

- Builder button is now added to the Wallets area to send the user, (and dummy data removed)
Screenshot 2024-04-22 at 16 02 47


- "Scenarios" replaced "Lab" for ease of understanding. 
Screenshot 2024-04-22 at 16 03 26

- Contacts and Settings hidden until ready. 

These are temporary minor changes in the current release, and will be much better in next major release. 

let me know if theres anything else required changing for this milestone?

**Comment by decentration** [comment]
> > Question - I do not understand the setting of the target amount function. For example, I am sending 100 TUR from Turing to Managata for 50 TUR. This scenario doesn’t really make sense, since if the token is the same they should be 1:1 mapped. Besides, since the unit per second is set in chain configs, for xToken transfer, there’s no way for users to specify the target amount to whatever they want. CleanShot 2024-04-21 at 13 03 22
> > That said, the composed XCM message is different from the UI, in a sense that it doesn’t contain a targeted amount.
> > I’m curious, is there any pallet call that would allow user to set target amount?
> 
> This is due to multiple hops, you will always see the sending amount in the action bar, for example if you have a multi hop scenario like this: Screenshot_2024-04-22_14-26-12
> 
> The action node in the middle displays the action, you only need to set the amount in the chain node your sending from

@chrisli30 in the next version if the target node is the last node in the flow then "amount" box will be hidden.

**Comment by chrisli30** [comment]
> > I’m blocked by this step to choose a correct target wallet on Moonriver. The Moonriver EVM address cannot be converted from Polkadot address, so an xToken transfer always needs manual selection of target wallet.
> 
> We have investigated this and we have added support for converting substrate accountid32 to evm addresses, however this is not universially stable, therefor we recommend to follow the video and manually select ur evm address(The problem is that the acocunt key generation for evm accounts/accountid20 types is not always working, so only some wallets lets you export your private key and convert it to a eth address, resulting in it being very hard for most polkadot account users to convert there ss58 seed to an eth address, resulting in problems accessing funds, this is the most stable way right now, we might add a filter moonriver nodes). Resources: https://github.com/polkadot-js/common/blob/f23f0944a85a6ddff72a8cd5866e85fd88edea39/packages/util-crypto/src/address/addressToEvm.ts#L9 unique is converting using the above functionality: https://github.com/UniqueNetwork/ts_api/blob/0d44ee0fdabd72a7c2225f32ab483a4eb8af4b05/src/utils/address/substrate.ts#L156C1-L157C1 astar mentions this: https://medium.com/astar-network/using-astar-network-account-between-substrate-and-evm-656643df22a0 same conversion in bagpipes: https://github.com/XcmSend/app/blob/1062a0f9e911f9930c2d9c18358d0a6528f9f484/src/Chains/Helpers/txHelper.ts#L19

@flipchan yes, we are on the same page. For Moonbeam, there is no way to auto-convert from a Substrate address to EVM one due to different key generations, so UI always needs to handle reading two wallets. Astar allows address conversion. 

Let me re-test the flows and see if I could successfully make the transfer.

**Comment by chrisli30** [comment]
> btw, thanks for the feedback!
> 
> We are also working on the next larger release of bagpipes UI, which will include a new look similar to the UI mockups you received; and the ability for users to persist scenarios, which is going to be a game changer; also the ability to use logic pills to make condition based data flows... so a bunch of stuff will also be improved the OAK integrations will naturally benefit from those releases too.

I believe the persist scenarios, or scenario history would be very helpful to users, as they can see and re-use the ones from the past. Will this change be included in M1, or will any future UI changes affect the page?

**Comment by chrisli30** [comment]
The M1 documentation mentions an HRMP channel check, but the chain selection of the target list doesn’t filter chains that are connected to the source. In our case, we should hide any chains that are not connected to Turing Network. Users wouldn’t have any idea what are available and what not.
CleanShot 2024-04-28 at 22 47 36

**Comment by chrisli30** [comment]
UI Issue: The 'from' and 'to' chains in the middle operator remain unchanged when different chains are selected.

CleanShot 2024-04-28 at 22 55 39

**Comment by chrisli30** [comment]
> > > I’m blocked by this step to choose a correct target wallet on Moonriver. The Moonriver EVM address cannot be converted from Polkadot address, so an xToken transfer always needs manual selection of target wallet.
> > 
> > 
> > We have investigated this and we have added support for converting substrate accountid32 to evm addresses, however this is not universially stable, therefor we recommend to follow the video and manually select ur evm address(The problem is that the acocunt key generation for evm accounts/accountid20 types is not always working, so only some wallets lets you export your private key and convert it to a eth address, resulting in it being very hard for most polkadot account users to convert there ss58 seed to an eth address, resulting in problems accessing funds, this is the most stable way right now, we might add a filter moonriver nodes). Resources: https://github.com/polkadot-js/common/blob/f23f0944a85a6ddff72a8cd5866e85fd88edea39/packages/util-crypto/src/address/addressToEvm.ts#L9 unique is converting using the above functionality: https://github.com/UniqueNetwork/ts_api/blob/0d44ee0fdabd72a7c2225f32ab483a4eb8af4b05/src/utils/address/substrate.ts#L156C1-L157C1 astar mentions this: https://medium.com/astar-network/using-astar-network-account-between-substrate-and-evm-656643df22a0 same conversion in bagpipes: https://github.com/XcmSend/app/blob/1062a0f9e911f9930c2d9c18358d0a6528f9f484/src/Chains/Helpers/txHelper.ts#L19
> 
> @flipchan yes, we are on the same page. For Moonbeam, there is no way to auto-convert from a Substrate address to EVM one due to different key generations, so UI always needs to handle reading two wallets. Astar allows address conversion.
> 
> Let me re-test the flows and see if I could successfully make the transfer.


Alright, I managed to execute the xTransfer. The issue lies within Talisman, which failed to prompt for wallet selection. Therefore, I couldn't select my EVM wallet address on the Moonriver chain. The XCM message works fine for xToken transferMutiasset.

**Comment by decentration** [comment]
> UI Issue: The 'from' and 'to' chains in the middle operator remain unchanged when different chains are selected.
> 
> CleanShot 2024-04-28 at 22 55 39

You need to click fetch button again to refresh the workflow.

We won’t automate this until next release this is outside the scope of this milestone.

**Comment by flipchan** [comment]
> persist scenarios

persist scenarios are out of scope for this milestone but we are working hard to get that feature alive, as we are testing and improving Bagpipes persistence execution environment(github.com/xcmsend/threadbag) Threadbag.

**Comment by flipchan** [comment]
@chrisli30 i have made the sending to moonriver more safe where it checks if the user has select an evm wallet so that users do not send to regular substrate accounts and burn there funds, left a video here:
https://drive.google.com/file/d/18-Qk6s6_9QpNwYn980hdPei7e_UNAX0y/view

**Review by chrisli30 — APPROVED** [review]
Although the parameters for the M1 deliveries have shifted slightly, with the successful cross-chain asset transfer to Moonriver, I'm keen to wrap up the M1 delivery to support your progress and keep momentum going. 

Additionally, we confirmed all Bagpipe future enhancements and bug fixes will be added to our scenarios. Look forward to M2!

**Comment by chrisli30** [comment]
Nice job on the M1 delivery! Funds have been sent: https://etherscan.io/tx/0x82cd2ea6d03881acdfcdc1877f9275c791f45b8527fce92f103051aa0b3dd3f4

Keep up the fantastic work, team! 👏

**Pull request merged**
