### PR TITLE
motoDEX Grant

### PR DESCRIPTION
**Pull request by oleksiivinogradov**
### Project Abstract

> Please provide a brief description of your project here summarizing key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/OAK-Foundation/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000
- [x] **Level 2**:  Up to $50,000
- [ ] **Level 3**:  Up to $250,000, OAK Network Council approval required

### Application Checklist

- [x] The [application template](https://github.com/OAK-Foundation/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x ] **A Ethereum Mainnet wallet address** for the payment of ERC20 USDC is provided inside the application.
- [x ] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/OAK-Foundation/Grants-Program/deliveries/README.md).

### CODE REVIEW

**Comment by chrisli30** [comment]
Hi @oleksiivinogradov, thank you for submitting the grant proposal. From the description provided, is it correct that your game is implemented with an EVM smart contract?

**Comment by oleksiivinogradov** [comment]
> Hi @oleksiivinogradov, thank you for submitting the grant proposal. From the description provided, is it correct that your game is implemented with an EVM smart contract?

Hi, yes, we are. Core and NFT smart contracts

**Comment by chrisli30** [comment]
@oleksiivinogradov, got it. Unfortunately our chain does not currenlty support EVM smart contract, making it unfeasible to deploy the contracts for your solution at this time. We’ll definitely reach out to you once the EVM capability is added!

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov, got it. Unfortunately our chain does not currenlty support EVM smart contract, making it unfeasible to deploy the contracts for your solution at this time. We’ll definitely reach out to you once the EVM capability is added!

No worries, we can create non-evm verson too. We already done rust near, rust concordium, Ink pokadot e.t.c.

**Pull request closed without merging**
