### PR TITLE
Create alphaday.md

### PR DESCRIPTION
**Pull request by Mikael337**
### Project Abstract

We would like to create a Oak Network ecosystem dashboard that aggregates useful information into a single free-to-use community dashboard.

### For which grant [level](https://github.com/OAK-Foundation/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000
- [ ] **Level 2**:  Up to $50,000
- [ ] **Level 3**:  Up to $250,000, OAK Network Council approval required

### Application Checklist

- [x] The [application template](https://github.com/OAK-Foundation/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] **A Ethereum Mainnet wallet address** for the payment of ERC20 USDC is provided inside the application.
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/OAK-Foundation/Grants-Program/deliveries/README.md).

### CODE REVIEW

**Comment by chrisli30** [comment]
Hi @Mikael337, thanks for your submission. This is a very interesting concept, as I anticipate that users would appreciate having an all-in-one board for projects.

Just to confirm, would the board be delivered on your site as a project in the BOARDS tab, like this: https://app.alphaday.com/b/oak/? Is my understanding correct?

**Comment by Mikael337** [comment]
Hello @chrisli30,

Thank you for your reply.

Yes, that is correct; Oak would have its own url and board as you stated.

**Comment by Mikael337** [comment]
Hi @chrisli30,

Are there any updates on our application yet? Please let me know if there are any other questions or requirements.

**Comment by chrisli30** [comment]
Hey @Mikael337, thank you for your proposal. After careful review, we opt not to approve this proposal, as it does not leverage our cross-chain automation. If we change the decision later, we’ll reach out to you!

**Comment by Mikael337** [comment]
Hello @chrisli30, thank you for your time and consideration. Feel free to contact me via Telegram (@MikeJacob3) as well, in case anything changes.

**Pull request closed without merging**
